Task_1_1_1
Zarcer/OOP pull request #1
Opened 2024-09-09 09:33 UTC by Zarcer

2024-09-11 16:26 UTC, galinabykova requested changes
исправь замечания ревьюдог и напиши, пожалуйста, своё имя (здесь или в лс тг)

2024-09-11 16:26 UTC, galinabykova commented on Task_1_1_1/docs/allclasses-index.html
удали ненужные файлики)

2024-09-11 16:26 UTC, galinabykova commented on Task_1_1_1/EXEL_GRAPH.png
а как ты замерял время?

2024-09-11 17:18 UTC, Zarcer commented on Task_1_1_1/EXEL_GRAPH.png
int[] sizes = new int[] {1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000, 15000000, 20000000};
        int n = sizes.length;
        for(int i = 0; i<n;i++)
        {
            int[] arr = generteArray(sizes[i]);
            long StartTime = System.currentTimeMillis();
            heapsort(arr);
            long EndTime = System.currentTimeMillis();
            long duration = EndTime-StartTime;
            System.out.println(sizes[i]+" | "+duration);
        }
        
        
        
        static int[] generteArray(int size) {
        int[] genarr = new int[size];
        for(int i = 0;i<size;i++)
        {
            genarr[i] = (int)(Math.random() * 1000);
        }
        return genarr;
    }

2024-09-11 17:20 UTC, Zarcer commented
> исправь замечания ревьюдог и напиши, пожалуйста, своё имя (здесь или в лс тг)

Летов. Там по ревьюдогу осталось два замечания, что у меня import static не в одной группе, но между ними же нет полей и они идут после нестатического импорта. Ну и по джавадоку у меня все функции с параметрами покрыты, у всего остального же пустой будет док, нет?

2024-09-12 04:30 UTC, galinabykova approved these changes

2024-09-12 05:05 UTC, merged