Task_1_1_2
Zarcer/OOP pull request #2
Opened 2024-09-15 04:40 UTC by Zarcer

2024-09-16 13:16 UTC, Zarcer commented
Я потестировал проблему с Exception ещё на винде, та же ошибка выскакивает у меня выскакивает, также ещё посмотрел и оно всегда весь инпут считывает, это нормальное поведение, вот ещё значения достал, первое, у того у кого работает нормально(на винде), второе моё(на линуксе) @galinabykova 
1)java.util.Scanner[delimiters=\p{javaWhitespace}+][position=1][match valid=true][need input=false][source closed=false][skipped=false][group separator=\x{a0}][decimal separator=\x{2c}][positive prefix=][negative prefix=\Q-\E][positive suffix=][negative suffix=][NaN string=\Qне число\E][infinity string=\Q∞\E]
2)java.util.Scanner[delimiters=\p{javaWhitespace}+][position=1][match valid=true][need input=false][source closed=false][skipped=false][group separator=\x{2c}][decimal separator=\x{2e}][positive prefix=][negative prefix=\Q-\E][positive suffix=][negative suffix=][NaN string=\QNaN\E][infinity string=\Q∞\E]

2024-09-17 03:59 UTC, galinabykova requested changes
Мягкий засчитан, но не затягивай с правками, судя по коду, тебе ещё много менять на жёсткий, а все правки я не могут выкатить сразу, потому что код должен сильно изменится, пока ты будешь исправлять текущие правки

Разобралась с проблемой. Тебе нужно создавать scanner один раз, потому что все данные он сохраняет в свой буфер, а потом разбивает по строчкам.

2024-09-17 03:59 UTC, galinabykova commented on Task_1_1_2/build/classes/java/test/ru/nsu/zarcer/CardTest.class
удали ненужные файлики

2024-09-17 03:59 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Deck.java
> +        deck_for_shuffle[0] = new Card("Двойка Трефы", 2);
перепиши на цикл

2024-09-17 03:59 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Card.java
> +    String Name;
лучше не давать доступ к полям вне класса
https://javarush.com/groups/posts/1928-getterih-i-setterih
однако у геттеры-сеттеры также не нужно расставлять бездумно
https://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html

2024-09-17 03:59 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +                if(sum == 21) {
магическая константа

2024-09-17 03:59 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +public class Round {
нужно декомпозировать методы в этом классе: выделить отдельные шаги, вынести эти отдельные шаги в отдельные методы. Например, можно сделать отдельный метод для вывода карт

2024-09-17 15:54 UTC, galinabykova requested changes

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/build/classes/java/main/ru/nsu/zarcer/Card.class
удали все ненужные файлики (для этого недостаточно удалить их из директории, нужно использовать git rm)

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Gameplay.java
> +    public static int critical_number_21 = 21;
так как эта переменная никогда не меняется, её надо сделать final и именовать как константу (в нашем стиле кода java google style используют верхний регистр)

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +        while(sum_dealer<17) {
это тоже магическая константа

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Hands.java
> +        for(int i = 0;i<52;i++) {
а зачем этот цикл?

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Deck.java
> +        for(int i = 0; i < 4; i++) {
тут, наверно не 4, а suit.length

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Deck.java
> +        String[] number = new String[] {"Двойка", "Тройка", "Четвёрка", "Пятёрка", "Шестёрка", "Семёрка", "Восьмёрка", "Девятка", "Десятка", "Валет", "Дама", "Король", "Туз"};
final

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Deck.java
> +        String[] suit = new String[] {"Трефы", "Бубны", "Черви", "Пики"};
final

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Deck.java
> +    public static Card[] createDeck() {
массив можно перемешать с помощью библиотечного shuffle, замени на него и удали все вспомогательные штуки для перемешивания

2024-09-17 15:54 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Gameplay.java
> +public class Gameplay {
а почему ты решил сделать тут все поля статические?

2024-09-17 18:01 UTC, Zarcer commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Hands.java
> +        for(int i = 0;i<52;i++) {
У меня без него программа ломается, как я понял нужно всегда инициализировать чем-то массивы в джаве, иначе у меня вылетает ошибка

2024-09-17 18:02 UTC, Zarcer commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Gameplay.java
> +public class Gameplay {
Если не буду использовать, то придётся создавать экземпляр класса Gameplay(это неудобно, т.к. у меня там много чекеров и флагов), а статические позволяют не делать этого

2024-09-18 02:24 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Hands.java
> +        for(int i = 0;i<52;i++) {
Скорее всего, ты пропускал инициализацию объекта. Посмотри вот этот пример
https://onlinegdb.com/C2Z_i5Qp-

2024-09-18 02:43 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Gameplay.java
> +public class Gameplay {
то есть фактически ты таким образом делаешь глобальные переменные для всего кода? Это не очень хорошо, так как код каждого класса начинает зависеть от какие-то неожиданные вещей, лучше, когда всё, что нужно, ты передаёшь в конструктор класса. Нужно переделать так, чтобы у тебя не осталось публичный не константных (то есть неизменяемых по сути, а не просто в final) полей

2024-09-18 03:12 UTC, galinabykova requested changes
В твоём коде есть два типа классов: наборы статических переменных и  Card, который по сути является набором данных с доступом к ним без поведения. Сами по себе эти классы не плохи, их используют в определённых ситуациях, но, так как других классов нет, можно сказать, что у тебя нет объектной модели.

Рассмотрим, например, вот этот метод
```java
public static void withdraw(Card[] hand, Card[] deck, int[] number_cards) {
        int check = 0;
        int index = number_cards[0];
        while(check == 0) {
            int choice = (int)(Math.random()*52);
            if(deck[choice].getTaken()) {
                continue;
            }
            hand[index].setPoints(deck[choice].getPoints());
            hand[index].setName(deck[choice].getName());
            deck[choice].setTaken(true);
            check = 1;
            number_cards[0]++;
        }
    }
```

По идее рука и колода это разные объекты, и надо принимать в метод не массивы а объекты Hand и Deck, 

Эти строчки 
```java
int choice = (int)(Math.random()*52);
if(deck[choice].getTaken()) {
                continue;
}
```
По сути вытягивание карты из колоды. Они относятся только к колоде и являются частью её поведения. Логичнее было бы сделать отдельный метод в колоде для этого.

Вот это
```java
hand[index].setPoints(deck[choice].getPoints());
hand[index].setName(deck[choice].getName());
```
выглядит как замена одного объекта карты на другой, возможно, тут можно было бы написать
`hand[index] = new Card(...)`

Аналогично нужно пройтись по всему коду и выделить отдельные объекты, у которых есть **поведение**.  Я ожидаю, что у тебя появится хотя бы два-три таких класса

2024-09-18 16:34 UTC, galinabykova requested changes

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/zarcer/DeckTest.java
> +                check = 1;
кажется, тут можно сделать ассёрт в цикле

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/zarcer/DeckTest.java
> +            if(i==51) {
возможно этот if можно убрать, заменив условие выхода из цикла

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Hand.java
> +    public void addCardcnt() {
кажется, этот метод можно сделать приватным

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Hand.java
> +    public void setCards_number(int number) {
кажется, этот метод нигде не используется

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Hand.java
> +    public void setCard(Card insert, int place) {
этот метод можно сделать приватным

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +        System.out.print("Вы открыли карту " + player_hand.getCard(player_hand.getNumber_cards()-1).getName() + " (" + player_hand.getCard(player_hand.getNumber_cards()-1).getPoints() + ")\n\t Ваши к
`player_hand.getCard(player_hand.getNumber_cards()-1)`
в этом длинном повторяющемся выражении участвует только player_hand. Лучше сделать отдельный метод для последней карты (или возвращать её в withdraw)

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +    public static int player_show_cards(Hand player_hand) {
этот метод у тебя выполняет два действия, причём одно из них не очевидно из названия. А ещё у тебя здесь используется только Hand. Лучше будет сделать метод посчёта очков в Hand. Вывод карт тоже можно частично сделать в Hand (сделать метод, возвращающий строчку с перечислением всех карт)

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +    public static int player_show_cards(Hand player_hand) {
То есть надо
1. разделить подсчёт очков и вывод. Вывод перенести в Hand
2. избавиться от дублирующегося кода в player_show_cards и dealer_show_cards созданием метода toString в Hand

2024-09-18 16:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +    private static int player_score = 0;
а теперь избавься от неконстантных static, теперь они не должны упрощать код

2024-09-19 05:31 UTC, galinabykova requested changes
Исправь ревьюдог и доделай тесты

2024-09-19 05:31 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/zarcer/DeckTest.java
> +        int check = 0;
неиспользуемая переменная

2024-09-19 05:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +public class Round {
В Питоне нестатические методы от статических отличаются тем, что в нестатические первым аргументом передаётся ссылка на объект (обычно её называют self). Ты тут сделал что-то похожее, передавая в каждый статический метод раунд. Предлагаю сделать методы не статическими и не передавать в них Round

2024-09-20 04:44 UTC, galinabykova requested changes

2024-09-20 04:44 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Gameplay.java
> +    public static final int CRITICALNUMBER21 = 21;
обычно всё-таки отделяют нижним подчёркиванием: CRITICAL_NUMBER21

2024-09-20 04:44 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/zarcer/Round.java
> +    int roundcount;
нужно сделать все поля private

2024-09-20 06:52 UTC, galinabykova approved these changes

2024-09-20 08:10 UTC, merged