Task_1_2_1
Zarcer/OOP pull request #4
Opened 2024-10-02 17:45 UTC by Zarcer

2024-10-04 09:07 UTC, galinabykova requested changes

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/Graph.java
> +interface Graph<T> {
интересный интерфейс) Мы здесь используешь идентификаторы, такой подход обычно используется в структурных языках программирования (например, дескрипторы в Си). Более "ооп-шно" было бы создать отдельный объект для вершин

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/TopologicalSort.java
> +    public List<T> sort() {
что произойдёт, если я дважды вызову этот метод? будет ли всё корректо работать?

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +                else if(Objects.equals(line, "EDGE")) {
кажется тут без else можно

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +            e.printStackTrace();
почему ты решил выбрать такой способ обработки исключения?

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +                    if(typeCheck instanceof String){
красивое решение

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +    AdjacencyList() {
наверно, надо тоже public, чтобы объект можно было создать

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +        adjList.get(firstVertexId).add(secondVertexId);
как будет вести себя программа, если индекс вершины будет некорректен?

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyMatrix.java
> +    public void readFile(String fileName) {
кажется, этот алгоритм не зависит от реализации, можно вынести его, чтобы была одна реализация для всех реализаций Graph. Сделай это

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyMatrix.java
> +        return -1;
в java не принято так сообщать об ошибке

2024-10-04 09:07 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyMatrix.java
> +            if(entry.getValue()==vertex) {
если ты тут осознанно используешь ==, поясни, почему так, если нет - почитай про разницу equals и ==

2024-10-04 15:18 UTC, Zarcer commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +            e.printStackTrace();
Везде где видел обработку чтения файла, так обрабатывают. Можно конечно с помощью throws просто кинуть исключение, но тогда придётся там где вызывается метод проверку делать

2024-10-04 15:36 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +            e.printStackTrace();
основная идея исключительных ситуация в том, чтобы пробросить исключение до того места, где тебе хватает информации для принятия решения. Я думаю, что это исключение стоит пробросить дальше, потому что здесь мы не знаем, как поступить с исключением, а наш пользователь может знать

2024-10-04 15:43 UTC, galinabykova requested changes
жду тесты)

2024-10-04 15:43 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +    public void addEdge(int firstVertexId, int secondVertexId) {
поведение при отсутствии вершины надо прописать в документации. Я бы тут, кстати, бросила исключение - потому что неверный индекс выглядит как явная ошибка, и чем скорее программист о ней узнает, тем лучше

2024-10-04 15:43 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/IncidenceMatrix.java
> +    public int getVertexId(T vertex) {
кажется, тут у тебя при попытке вернуть индекс вершины, которой нет, будет возвращён 0. Я бы тут сделала исключение, потому что это выглядит как ситуация, в которой лучше как можно раньше узнать о проблеме, а исключение прямо сигнализирует о ней

2024-10-04 15:43 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/IncidenceMatrix.java
> +    public int getVertexId(T vertex) {
а 0 как будто замолчит её

2024-10-05 09:19 UTC, galinabykova requested changes

2024-10-05 09:19 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +                throw new Exception("Invalid Id");
сейчас тут немного необычно поведение. Не стоит ловить исключение в том же методе, где ты его бросаешь, для таких ситуаций больше подходят обычные иф, так как они более быстрые. Исключения нужны, чтобы бросить исключение в одном месте, а обработать его выше по стеку вызовов. В этой ситуации логичнее будет добавить в сигнатуру addEdge throws Exception и не ловить его тут. Также стоит выбрать более специфичный тип исключения

2024-10-05 09:19 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/zarcer/AdjacencyList.java
> +                throw new Exception("Invalid Id");
пожалуйста, избавься от всех таких ситуаций в коде

2024-10-05 15:52 UTC, galinabykova approved these changes

2024-10-05 18:18 UTC, merged