Task_1_4_1
Zarcer/OOP pull request #7
Opened 2024-10-12 11:42 UTC by Zarcer

2024-10-12 13:57 UTC, galinabykova requested changes

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/Semester.java
> +        int marksCnt = 0;
в этой лабе нужно использовать StreamAPI. Используй вместо цикла в этом методе StreamAPI

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/Semester.java
> +        for(Grades grade : records.values()){
замени цикл на StreamAPI

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/Semester.java
> +        for(Grades grade : records.values()){
тут и во всех методах этого класса

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/Semester.java
> +    private Map<ElectronicBook.typeControl, Grades> records;
у тебя, кажется. нигде не хранится название предмета. Но для расчёта среднего балла диплома он нужен, так как по предметам, которые идут два семестра, в диплом идёт последняя оценка

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +            if(i==7){
вот это условие не поняла

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +    public boolean checkRedDiploma(int currentSemester){
в этом методе тоже используй streamapi

2024-10-12 13:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +        if(currentSemester==1||currentSemester==2){
уточни, можно ли  во втором семестре повышенную стипендию получать, когда я училась, было можно

2024-10-13 06:25 UTC, Zarcer commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +            if(i==7){
Для красного диплома оценка на ВКР должна быть 5, тут у меня если цикл доходит до 7(то есть 8 семестра), то проверяется условие отдельно на ВКР

2024-10-13 06:25 UTC, Zarcer commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +        if(currentSemester==1||currentSemester==2){
![изображение](https://github.com/user-attachments/assets/ec40f5f3-1deb-4bcd-aabf-8b074cc59b01)

2024-10-13 14:34 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +            if(i==7){
а, поняла

2024-10-13 14:36 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +        if(currentSemester==1||currentSemester==2){
а, это ПГАС, оки)

2024-10-13 14:46 UTC, galinabykova requested changes
жду тесты)

2024-10-13 14:46 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +            if(i==7){
мне кажется, это условие можно вынести за цикл

2024-10-13 14:46 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/zarcer/ElectronicBook.java
> +        for(int i = 0;i<currentSemester;i++){
попробуй заменить этот цикл на стрим апи тоже

2024-10-14 04:49 UTC, galinabykova requested changes
ещё одна правка и всё)

2024-10-14 04:49 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/zarcer/ElectronicBookTest.java
> +    public void checkRedDiplomaTest() {
по красному диплому много условий, хотелось бы тесты на проверку их всех. То есть тест, когда у студента 4 за ВКР, отдельно тест, где у студента есть 3, отдельно, где средний балл не подходит. Важно, чтобы в тесте остальные условия (кроме проверяемого) выполнялись, чтобы проверить именно его

2024-10-14 07:58 UTC, galinabykova approved these changes

2024-10-14 07:58 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/zarcer/ElectronicBookTest.java
> +    public void checkRedDiplomaTest() {
лучше бы сделать их в отдельных тестах. Сейчас, если на первом ассёрте тест упадёт второе условие просто не проверится

2024-10-14 08:03 UTC, merged