Task_1_1_3 additionalTask
Zarcer/OOP pull request #8
Opened 2024-10-13 11:51 UTC by Zarcer

2024-10-13 14:52 UTC, galinabykova requested changes

2024-10-13 14:52 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/zarcer/Sub.java
> +            int result = this.eval("x = 666");
красивое число, но имхо, пустая строка была бы более понятной)

2024-10-13 14:52 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/zarcer/Sub.java
> +            int result = this.eval("x = 666");
но идея прикольная, правда меня немного смущает, что код дублируется много раз. Можно было его перенести в Expression

2024-10-13 14:52 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/zarcer/Add.java
> +//        if(!first.checkVariable() && !second.checkVariable()){
а почему тут закоммитил?)

2024-10-14 03:22 UTC, Zarcer commented on Task_1_1_3/src/main/java/ru/nsu/zarcer/Add.java
> +//        if(!first.checkVariable() && !second.checkVariable()){
у меня не работал кат и я тестировал, забыл убрать

2024-10-14 04:51 UTC, galinabykova approved these changes

2024-10-14 04:51 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/zarcer/Expression.java
> +    public Expression checkAndFinale(Expression first, Expression second) {
мне кажется, тут бы хватило protected

2024-10-14 07:23 UTC, merged